#' Population estimation using a fixed hierarchical model
#'
#' Estimates the total population, including the unobserved population, using
#' a specified hierarchical log-linear model.
#'
#' Optional bootstrap and jackknife calculations provide BCa confidence
#' intervals while fitting the same fixed model to every resampled data set.
#'
#' @param zdat A capture history data matrix with \eqn{t+1} columns. The first
#' \eqn{t} columns correspond to the capture lists and contain zeros and ones
#' defining the observed capture histories. The final column contains the
#' number of cases having each capture history. Capture histories not
#' explicitly included in the data are assumed to have zero count.
#'
#' @param model A character string specifying a hierarchical log-linear
#' model by its maximal interactions. For example, \code{"[12,23]"} specifies
#' the hierarchical model generated by interactions 12 and 23, including all
#' implied lower-order terms. If \code{NULL}, the main-effects model is used.
#' The default is \code{NULL}.
#'
#' @param nboot Non-negative integer giving the number of bootstrap
#' replications. If \code{nboot = 0}, only the point estimate and fitted model
#' are returned and no bootstrap or jackknife calculations are performed.
#' The default is 0.
#'
#' @param iseed Integer seed used to initialise the random-number generator
#' when \code{nboot > 0}. The default is 1234.
#'
#' @param alpha Numeric vector of cumulative probability levels at which the
#' endpoints of the BCa confidence intervals are to be calculated. This
#' argument is used only when
#' \code{nboot > 0}. The default is
#' \code{c(0.025, 0.1, 0.9, 0.975)}.
#'
#' @param return_details Logical. If \code{TRUE}, include the original-data
#' GLM fit, bootstrap estimates, BCa acceleration, and effects estimated at
#' minus infinity. The default is \code{FALSE}.
#'
#' @details
#' The specified hierarchical model is fitted to the observed data.
#' Parameter identifiability and existence of the extended MLE are checked
#' for the original data and for every bootstrap and jackknife data set.
#' Parameters whose extended-MLE values are minus infinity are handled by
#' the fitting routine.
#'
#' If \code{nboot > 0}, multinomial bootstrap samples are generated from the
#' observed capture history counts. The same fixed hierarchical model is
#' fitted to every bootstrap sample. Unlike
#' \code{\link{estimate_population_stepwise}}, there is no model-selection
#' step within the bootstrap replications.
#'
#' Bootstrap replications for which the fixed model cannot be fitted are
#' omitted with a warning. If the model cannot be fitted to any bootstrap
#' sample, the routine stops with an error.
#'
#' A delete-one jackknife calculation is also carried out to estimate the
#' acceleration parameter required for the BCa confidence intervals. If the
#' fixed model cannot be fitted after a positive-count deletion, the routine
#' stops with an informative error.
#'
#' A small positive value of \code{nboot}, such as that used in the example,
#' is useful only for checking that the routine runs. A substantially larger
#' number of bootstrap replications should be used for substantive inference.
#'
#' @return A list with components:
#' \describe{
#'   \item{\code{input}}{A list containing the original \code{call} and
#'   \code{data}.}
#'   \item{\code{method}}{The character string \code{"fixed"}.}
#'   \item{\code{estimate}}{A named numeric vector containing the estimated
#'   \code{dark_figure} and \code{total} population.}
#'   \item{\code{fitted_model}}{The hierarchy fitted to the original data.}
#'   \item{\code{uncertainty}}{A two-row matrix of BCa endpoints for the dark
#'   figure and total population when \code{nboot > 0}; otherwise an
#'   explanatory character string.}
#'   \item{\code{details}}{If \code{return_details = TRUE}, a list containing
#'   \code{minus_infinity_effects}, \code{bootstrap_estimates},
#'   \code{bca_acceleration}, and \code{glm_fit}. The last is the complete
#'   conditional GLM fit for the fixed model. Otherwise
#'   \code{"not requested"}.}
#' }
#'
#' @references
#' Chan, L., Silverman, B. W., and Vincent, K. (2021).
#' Multiple Systems Estimation for Sparse Capture Data: Inferential
#' Challenges when there are Non-Overlapping Lists.
#' \emph{Journal of the American Statistical Association},
#' \strong{116}(535), 1297--1306.
#' Available from
#' \url{https://www.tandfonline.com/doi/full/10.1080/01621459.2019.1708748}.
#'
#' DiCiccio, T. J. and Efron, B. (1996).
#' Bootstrap Confidence Intervals.
#' \emph{Statistical Science}, \strong{11}(3), 189--228.
#'
#' @examples
#' data(Korea)
#'
#' # Main-effects model without bootstrapping
#' estimate_population_fixed(Korea)
#'
#' # A fixed pairwise-interaction model using hierarchy notation
#' estimate_population_fixed(Korea, model = "[23,1]")
#'
#' # A very small number of bootstrap replications is used here only
#' # to keep the example quick.
#' estimate_population_fixed(
#'   Korea,
#'   model = "[23,1]",
#'   nboot = 2
#' )
#'
#' @export
estimate_population_fixed <- function(
    zdat,
    model = NULL,
    nboot = 0,
    iseed = 1234,
    alpha = c(0.025, 0.1, 0.9, 0.975),
    return_details = FALSE
) {
  call <- match.call()
  if (length(nboot) != 1L ||
      is.na(nboot) ||
      nboot < 0 ||
      nboot != as.integer(nboot)) {
    stop("`nboot` must be a non-negative integer.", call. = FALSE)
  }

  nlists <- ncol(zdat) - 1L

  ing_dat <- ingest_data(zdat)

  if (is.null(model)) {
    model <- paste0(
      "[",
      paste(seq_len(nlists), collapse = ","),
      "]"
    )
  }

  MSEfit <- fit_hier_model(
    xdatin = ing_dat,
    hiermod = model,
    checkid = TRUE
  )

  popest <- unname(MSEfit$abundance)
  if (!is.finite(popest)) {
    stop(
      paste0(
        "No finite population-size estimate exists for the original data ",
        "under the specified fixed hierarchical model."
      ),
      call. = FALSE
    )
  }

  if (nboot == 0L) {
    details <- if (return_details) {
      list(
        minus_infinity_effects = .mse_effect_names(MSEfit$neginfpars, zdat),
        bootstrap_estimates = "not generated because nboot = 0",
        bca_acceleration = "not calculated because nboot = 0",
        glm_fit = MSEfit
      )
    } else {
      "not requested"
    }

    return(list(
      input = list(call = call, data = zdat),
      method = "fixed",
      estimate = .mse_estimate(popest, zdat),
      fitted_model = model,
      uncertainty = .mse_uncertainty(NULL, zdat),
      details = details
    ))
  }
  set.seed(iseed)

  n1 <- nrow(zdat)
  n2 <- ncol(zdat)
  countsobserved <- zdat[, n2]
  nobs <- sum(countsobserved)

  # Generate bootstrap estimates using the same fixed hierarchical model.
  bootreps <- rep(NA_real_, nboot)

  for (j in seq_len(nboot)) {
    counts <- as.vector(
      stats::rmultinom(
        n = 1,
        size = nobs,
        prob = countsobserved
      )
    )

    zdatboot <- cbind(
      zdat[, -n2, drop = FALSE],
      counts
    )

    bootfit <- fit_hier_model(
      xdatin = ingest_data(zdatboot),
      hiermod = model,
      checkid = TRUE
    )

    bootreps[j] <- bootfit$abundance
  }

  # Omit bootstrap replications for which the fixed model could not be fitted.
  usable_bootreps <- is.finite(bootreps)
  nfailed <- sum(!usable_bootreps)

  if (!any(usable_bootreps)) {
    stop(
      paste0(
        "No bootstrap replication produced a finite population-size ",
        "estimate under the specified fixed hierarchical model."
      ),
      call. = FALSE
    )
  }

  if (nfailed > 0L) {
    warning(
      nfailed,
      " of ",
      nboot,
      " bootstrap replications did not produce a finite population-size ",
      "estimate under the specified fixed hierarchical model and were omitted.",
      call. = FALSE
    )

    bootreps <- bootreps[usable_bootreps]
  }

  # Delete-one jackknife estimates for the BCa acceleration.
  jackest <- rep(0, n1)

  for (j in seq_len(n1)) {
    nj <- zdat[j, n2]

    if (nj > 0) {
      zd1 <- zdat
      zd1[j, n2] <- nj - 1

      jackfit <- fit_hier_model(
        xdatin = ingest_data(zd1),
        hiermod = model,
        checkid = TRUE
      )

      if (!is.finite(jackfit$abundance)) {
        capture_history <- paste0(zdat[j, -n2], collapse = "")

        stop(
          paste0(
            "BCa confidence intervals cannot be calculated: after deleting one ",
            "individual from capture history ",
            capture_history,
            " (row ",
            j,
            "), no finite population-size estimate exists under the specified ",
            "fixed hierarchical model."
          ),
          call. = FALSE
        )
      }

      jackest[j] <- jackfit$abundance
    }
  }

  jr <- (
    sum(countsobserved * jackest) /
      sum(countsobserved)
  ) - jackest

  ahat <- sum(countsobserved * jr^3) /
    (6 * sum(countsobserved * jr^2)^(3 / 2))

  confquantiles <- bcaconfvalues(
    bootreps,
    popest,
    ahat,
    alpha
  )

  details <- if (return_details) {
    list(
      minus_infinity_effects = .mse_effect_names(MSEfit$neginfpars, zdat),
      bootstrap_estimates = bootreps,
      bca_acceleration = ahat,
      glm_fit = MSEfit
    )
  } else {
    "not requested"
  }

  list(
    input = list(call = call, data = zdat),
    method = "fixed",
    estimate = .mse_estimate(popest, zdat),
    fitted_model = model,
    uncertainty = .mse_uncertainty(confquantiles, zdat),
    details = details
  )
}
